logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    com.tontine.app: INFO

management:
  metrics:
    export:
      prometheus:
        enabled: false

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/tontine
    username: postgres
    password: hoangduy321
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: tech.jhipster.domain.util.FixedPostgreSQL10Dialect
  liquibase:
    contexts: prod
    enabled: false
  main:
    lazy-initialization: true
    banner-mode: off

server:
  port: 8081
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

jhipster:
  cache:
    caffeine:
      max-entries: 1000
      time-to-live-seconds: 3600
  http:
    cache:
      timeToLiveInDays: 1461
  security:
    authentication:
      jwt:
        base64-secret: MmM4NzE2ZDkzZTIxYzg3MjYyZDU4NjkwNDllYTg2ZGE5MDI4OWZiM2ExZGM4NTkyYTgwOGVkNzhhNWMzMjRmYTRkNWUyYjU4OGQzOWIwMjZkMzM0Yjg1NmI0YWY2ZjczODFhNTUxZjc1MzA1ZjNiMTA0ODM5MWMzY2VhNzgyMGQ=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
